id: P009142
initial_creation_type: ocr
source_metadata:
  id: bdr:W20235
  title: ཁྲེང་ཀོན་ཆུས
  author: ''
  volumes:
    393d70f7b3a947c1853e5605aa482e9d:
      image_group_id: I1GS55149
      title: ''
      volume_number: 1
      total_pages: 144
