id: I6AF45451
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T11:04:53+00:00'
last_modified: '2022-06-08T08:55:15.336360+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20235
  title: ཁྲེང་ཀོན་ཆུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    A54B:
      image_group_id: I1GS55149
      title: ''
      total_pages: 144
      order: 1
      base_file: A54B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
